service: todo-list

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  deploymentBucket:
    blockPublicAccess: true
  iam:
    role: ${file(./infra/permissions.yml):role}
  environment:
    NODE_ENV: ${self:custom.variables.NODE_ENV}
  tracing:
    lambda: true
    apiGateway: true

custom:
  variables:
    NODE_ENV: ${self:provider.stage}
    DYNAMODB_TABLE_NAME: task-table-${self:provider.stage}
    DYNAMODB_DAILY_TASKS_INDEX_NAME: list_daily_tasks_index

plugins:
  - serverless-plugin-typescript

resources: ${file(./infra/resources.yml)}

package:
  individually: false
  excludeDevDependencies: true

functions: ${file(./infra/functions.yml)}
