'create-task':
  handler: src/usecases/create-task/index.handler
  description: create task
  events:
    - http:
        path: /list/{taskListId}/task/
        method: post
        request:
          parameters:
            paths:
              taskListId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'list-tasks':
  handler: src/usecases/list-tasks/index.handler
  description: list tasks
  events:
    - http:
        path: /list/{taskListId}/tasks
        method: get
        request:
          parameters:
            paths:
              taskListId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}
    DYNAMODB_DAILY_TASKS_INDEX_NAME: ${self:custom.variables.DYNAMODB_DAILY_TASKS_INDEX_NAME}

'find-task':
  handler: src/usecases/find-task/index.handler
  description: find task with the given ID
  events:
    - http:
        path: /list/{taskListId}/task/{taskId}
        method: get
        request:
          parameters:
            paths:
              taskId: true
              taskListId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'update-task':
  handler: src/usecases/update-task/index.handler
  description: update task with the given ID
  events:
    - http:
        path: /list/{taskListId}/task/{taskId}
        method: patch
        request:
          parameters:
            paths:
              taskId: true
              taskListId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'delete-task':
  handler: src/usecases/delete-task/index.handler
  description: delete task with the given ID
  events:
    - http:
        path: /list/{taskListId}/task/{taskId}
        method: delete
        request:
          parameters:
            paths:
              taskId: true
              taskListId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'create-list':
  handler: src/usecases/create-list/index.handler
  description: create list
  events:
    - http:
        path: /username/{username}/list
        method: post
        request:
          parameters:
            paths:
              username: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'list-lists':
  handler: src/usecases/list-lists/index.handler
  description: list lists
  events:
    - http:
        path: /username/{username}/lists
        method: get
        request:
          parameters:
            paths:
              username: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}
