'create-task':
  handler: src/usecases/create-task/index.handler
  description: create task
  events:
    - http:
        path: /
        method: post
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'list-tasks':
  handler: src/usecases/list-tasks/index.handler
  description: list tasks
  events:
    - http:
        path: /
        method: get
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}
    DYNAMODB_DAILY_TASKS_INDEX_NAME: ${self:custom.variables.DYNAMODB_DAILY_TASKS_INDEX_NAME}

'find-task':
  handler: src/usecases/find-task/index.handler
  description: find task with the given ID
  events:
    - http:
        path: /{taskId}
        method: get
        request:
          parameters:
            paths:
              taskId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'update-task':
  handler: src/usecases/update-task/index.handler
  description: update task with the given ID
  events:
    - http:
        path: /{taskId}
        method: patch
        request:
          parameters:
            paths:
              taskId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}

'delete-task':
  handler: src/usecases/delete-task/index.handler
  description: delete task with the given ID
  events:
    - http:
        path: /{taskId}
        method: delete
        request:
          parameters:
            paths:
              taskId: true
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.variables.DYNAMODB_TABLE_NAME}
