role:
  statements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        Fn::GetAtt:
          - TaskTable
          - Arn
