Resources:
  TaskTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: task-table-${self:provider.stage}
      AttributeDefinitions:
        - AttributeName: partition_key
          AttributeType: S
        - AttributeName: sort_key
          AttributeType: S
        - AttributeName: date_string
          AttributeType: S
      KeySchema:
        - AttributeName: partition_key
          KeyType: HASH
        - AttributeName: sort_key
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: list_daily_tasks_index
          KeySchema:
            - AttributeName: partition_key
              KeyType: HASH
            - AttributeName: date_string
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
